version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install container dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -qq gfortran liblapack-dev

      - run:
          name: Install python dependencies
          command: |
            mkdir -p venv
            virtualenv venv
            . venv/bin/activate
            # Hack to disable the progress bar
            set -o pipefail; pip install -r requirements.txt | cat

      - run:
          name: Show versions
          command: |
            . venv/bin/activate
            pip freeze

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make test
